name: PullRequest

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: rm -f ~/.m2/settings.xml
      - name: Build Hawkbit
        # do not run tests eclipse hawkbit will do it for us
        run: cd hawkbit && mvn clean install -DskipTests
      #- uses: actions/setup-java@v2
      #  with:
      #    distribution: 'adopt'
      #    java-version: '11'
      #    overwrite-settings: false
      #- run: rm -f ~/.m2/settings.xml
      - name: Build Inoa Hawkbit
        run: mvn clean install -Ddocker.image.version=${{ steps.prep.outputs.BUILD_ID }}
